
version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - TRANSMISSION_WEB_HOME=/flood-for-transmission/ #optional
    volumes:
      - /portainer/Files/AppData/Config/Transmission:/config
      - /hdd:/downloads
      - /hdd/torrents:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    
  pyload:
    image: lscr.io/linuxserver/pyload
    container_name: pyload
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /portainer/Files/AppData/Config/pyload:/config
      - /hdd/downloads:/downloads
    ports:
      - 8228:8000
      - 7227:7227
    restart: unless-stopped
